# Generated by Django 4.2.29 on 2026-03-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_employee_salarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.CharField(default='carpet', max_length=50),
        ),
        migrations.AddField(
            model_name='roll',
            name='category',
            field=models.CharField(default='carpet', max_length=50),
        ),
    ]
