# Generated by Django 4.2.29 on 2026-03-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_producttype_category_roll_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='roll',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='inventory.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('shop', 'name')},
        ),
    ]
