# Generated by Django 4.2.29 on 2026-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shop_alter_producttype_name_employee_shop_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='shop',
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
