# Generated by Django 4.2.29 on 2026-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_producttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roll',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roll',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
