# Generated by Django 4.2.29 on 2026-03-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_factory_factorypayment_roll_factory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=200)),
                ('customer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('date', models.CharField(max_length=50)),
                ('remarks', models.TextField(default='No remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.FloatField()),
                ('roll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.roll')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
        ),
    ]
