# Generated by Django 4.2.29 on 2026-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sale_saleitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='discount',
            new_name='balance_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Advance', 'Advance'), ('Udhar', 'Udhar')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Unpaid', 'Unpaid')], default='Paid', max_length=20),
        ),
    ]
