# Generated by Django 6.0.3 on 2026-04-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_discount_sale_balance_amount_sale_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
