# Generated by Django 6.0.3 on 2026-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='width',
            field=models.FloatField(default=12.0),
        ),
    ]
