# Generated by Django 4.2.29 on 2026-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_saleitem_quantity_saleitem_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorypayment',
            name='remarks',
            field=models.TextField(blank=True, default='No remarks', null=True),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='remarks',
            field=models.TextField(blank=True, default='No remarks', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remarks',
            field=models.TextField(blank=True, default='No remarks', null=True),
        ),
    ]
