# Generated by Django 4.2.29 on 2026-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_factorypayment_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
