# Generated by Django 6.0.3 on 2026-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_additionalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstock',
            name='color',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='additionalstock',
            name='design',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='additionalstock',
            name='stock_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='additionalstock',
            name='total_payment',
            field=models.FloatField(default=0),
        ),
    ]
