# Generated by Django 4.2.29 on 2026-04-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_additionalstock_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Unpaid', 'Unpaid'), ('Returned', 'Returned')], default='Paid', max_length=20),
        ),
    ]
