# Generated by Django 6.0.3 on 2026-04-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='received_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roll',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roll',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
